/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.bk.kotlinskills.kotlin-library-conventions")
}

dependencies {
    //api(project(":utilities"))

    implementation("org.apache.commons:commons-text:1.10.0")

}