/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.bk.kotlinskills.kotlin-library-conventions")
}

dependencies {
    //api(project(":utilities"))

    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
    implementation("com.microsoft.graph:microsoft-graph:5.77.0")
    implementation("org.apache.commons:commons-text:1.10.0")


}