/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("co.bk.kotlinskills.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("co.bk.kotlinskills.training.AppKt")
}

kotlin {
    compilerOptions {
        // Kotlin 2.1.0 experimental feature -> https://kotlinlang.org/docs/whatsnew21.html#guard-conditions-in-when-with-a-subject
        // freeCompilerArgs.add("-Xwhen-guards")
    }
}
