/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package co.bk.kotlinskills.utilities

import co.bk.kotlinskills.utilities.LinkedList

class StringUtils {
    companion object {
        fun join(source: LinkedList): String {
            return JoinUtils.join(source)
        }

        fun split(source: String): LinkedList {
            return SplitUtils.split(source)
        }
    }
}
